---
- hosts: allnode
  become: yes
  tasks:
    - name: Install requirements (swap,etc,folders)
      include_role:
        name: requirements
        tasks_from: requirements.yml

- hosts: master_firstnode
  become: yes
  tasks:
    - name: Include vars
      include_vars:
        dir: vars

    - name: Install RKE2 Master Server TASK
      include_role:
        name: installation
        tasks_from: install_master.yml     

- hosts: master_nextnodes
  become: yes
  tasks:
    - name: Include vars
      include_vars:
        dir: vars

    - name: Install RKE2 Next Master Nodes TASK
      include_role:
        name: installation
        tasks_from: join_master.yml  

- hosts: workers
  become: yes
  tasks:
    - name: Include vars
      include_vars:
        dir: vars

    - name: Install RKE2 Next Master Nodes TASK
      include_role:
        name: installation
        tasks_from: join_worker.yml  
  
- hosts: master_firstnode
  become: yes
  tasks:
    - name: Include vars
      include_vars:
        dir: vars

    - name: Wait for all node to be ready
      shell: kubectl wait --for=condition=Ready nodes --all --timeout=600s
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: nodes_ready
    - debug:
        msg: "All Nodes are ready \n {{nodes_ready.stdout_lines }}"