---
    - name: Create RKE2 Directory
      file:
        path: "{{ confdir }}"
        state: directory
        owner: root
        group: root
        mode: '0770'
        recurse: yes

    - name: Installing RKE2 Server
      shell: |
          curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL="{{ rke2_version }}" INSTALL_RKE2_TYPE="server" sh -
    
    - name: Start rke2-server service
      service:
        name: rke2-server
        state: started
        enabled: yes 
    
    - name: Simlink kubectl
      shell: |
        ln -s $(find /var/lib/rancher/rke2/data/ -name kubectl) /usr/local/bin/kubectl
      ignore_errors: true
    
    - name: Append /var/lib/rancher/rke2/bin/ to PATH env
      lineinfile:
        path: /root/.bash_profile
        line: export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
        create: yes
        backup: yes
    
    - name: Wait for first node to be ready
      shell: kubectl wait --for=condition=Ready nodes --all --timeout=600s
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: nodes_ready

    - debug: var=nodes_ready.stdout_lines   
    
    - name: Create RKE2 config.yaml for joining
      shell: "echo server: https://{{ ansible_host }}:9345 > {{ confvar }}/config.yaml; \
              echo token: $(cat {{ confvar }}/node-token) >> {{ confvar }}/config.yaml"

    - name: Fetch Token From Master
      fetch:
       src: "{{ confvar }}/config.yaml"
       dest: "/tmp/rke2_{{ clustername }}_config.yaml"
       flat: yes