---
  #- name: Wait 2 Minutes for RKE2 Master Server Node Ready
  #  pause:
  #    seconds: 120

  - name: Create RKE2 Directory
    file:
       path: "{{ confdir }}"
       state: directory
       owner: root
       group: root
       mode: '0770'
       recurse: yes

  - name: Installing RKE2 Server
    shell: |
        curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL="{{ rke2_version }}" INSTALL_RKE2_TYPE="server" sh -
    

  - name: Copy Master Rancher Config file
    copy:
     src: /tmp/rke2_{{ clustername }}_config.yaml
     dest: /etc/rancher/rke2/config.yaml
     owner: root
     group: root
     mode: '0660'

  - name: Start rke2-server service
    service:
      name: rke2-server
      state: started
      enabled: yes 
  
  - name: Simlink kubectl
    shell: |
      ln -s $(find /var/lib/rancher/rke2/data/ -name kubectl) /usr/local/bin/kubectl
    ignore_errors: true
  
  - name: Append /var/lib/rancher/rke2/bin/ to PATH env
    lineinfile:
      path: /root/.bash_profile
      line: export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
      create: yes
      backup: yes

